apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-db
  namespace: backend
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi